version: '3.8'

services:
  local_batch:
    build: ./docker/local/
    container_name: 'local_batch_python'
    working_dir: '/service/'
    tty: true
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Tokyo
    command: >
      bash -c '
        pip install -r src/requirements.txt
        while :; do sleep 10; done
      '
  gcp_batch:
    build: ./docker/gcp/
    container_name: 'gcp_batch_python'
    working_dir: '/service/'
    tty: true
    volumes:
      - ./src:/service/src
    ports:
      - 8010:8080
    environment:
      TZ: Asia/Tokyo
    command: >
      bash -c '
        pip install -r src/requirements.txt
        functions-framework --target=handler --signature-type=event
      '
  aws_batch:
    build: ./docker/aws/
    container_name: 'aws_batch_python'
    working_dir: '/var/task'
    tty: true
    ports:
      - 8020:8080
    volumes:
      - ./src:/var/task/src
      - ~/.aws:/root/.aws
    environment:
      TZ: Asia/Tokyo
    entrypoint: >
      bash -c '
      pip install -r src/requirements.txt &&
      /lambda-entrypoint.sh main.handler
      '
